version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
    - ./gate-simulator:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgresdb:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  java-app:
    build: .
    image: java-app:1.0
    ports:
      - '9999:9999'